In [7]:
import numpy as np
from mp_api.client import MPRester
from pymatgen.core.operations import SymmOp
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from pymatgen.electronic_structure.plotter import BSPlotter
from pymatgen.phonon.plotter import PhononBSPlotter
from jupyter_jsmol.pymatgen import quick_view
from lmapr1492 import plot_brillouin_zone, get_plot_bs, get_plot_dos, get_plot_bs_and_dos, get_branch_wavevectors
from plotly.subplots import make_subplots
import plotly.graph_objects as go

In [8]:
mp_key = "kUNltwLCR9AdLypQdV0AJRVJ3G9Yb7B8"
mp_id = "mp-8426"

In [9]:
with MPRester(mp_key) as m:
    prim_struc = m.get_structure_by_material_id(mp_id)
    el_bs = m.get_bandstructure_by_material_id(mp_id)
    el_dos = m.get_dos_by_material_id(mp_id)
    ph_bs = m.get_phonon_bandstructure_by_material_id(mp_id)
    ph_dos = m.get_phonon_dos_by_material_id(mp_id)
conv_struc = SpacegroupAnalyzer(prim_struc).get_conventional_standard_structure()
symmops = SpacegroupAnalyzer(conv_struc).get_space_group_operations()

Retrieving MaterialsDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Retrieving ElectronicStructureDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Retrieving ElectronicStructureDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Retrieving PhononBSDOSDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Retrieving PhononBSDOSDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

In [10]:
view = quick_view(conv_struc)
display(view)

JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [11]:
sym = SpacegroupAnalyzer(conv_struc).get_symmetry_operations()

#Atomes sélectionnés
Se1 = [1.0,1.0,1.0]
K = [0.25,0.25,0.25]
Se2 = [1.0,0.5,0.5]



S1 = sym[1]
S2 = sym[6]
S3 = sym[9]


Se1_sym = S1.operate(Se1)
K_sym = S2.operate(K)
Se2_sym = S3.operate(Se2)

#print(S1)
#print(S2)
#print(S3)


In [15]:
print("L'atome de départ a comme coordonnées: {}\n".format(Se1))

print("L'opérartion est une symétrie centrale par rapport au point origine. \n")
print(S1, "\n")

print("L'opération se calcule donc de la façon suivante : \n")
print(S1.rotation_matrix, "*", Se1, '+', S1.translation_vector, "\n")

print("L'atome d'arrivé a comme coordonnées : {}\n".format(Se1_sym))

#Représentation selon jupyter-jsmol
view = quick_view(conv_struc,supercell=[1,1,1])
display(view)
view.script('draw symop 2 {atomno = 4}; select atomno=4; label on; color red')

L'atome de départ a comme coordonnées: [1.0, 1.0, 1.0]

L'opérartion est une symétrie centrale par rapport au point origine. 

Rot:
[[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]]
tau
[0. 0. 0.] 

L'opération se calcule donc de la façon suivante : 

[[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]] * [1.0, 1.0, 1.0] + [0. 0. 0.] 

L'atome d'arrivé a comme coordonnées : [-1. -1. -1.]



JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [13]:
print("L'atome de départ a comme coordonnées: {}\n".format(K))

print("L'opérartion est une rotation de 90 degrés dans le plan xy. \n")
print(S2, "\n")

print("L'opération se calcule donc de la façon suivante : \n")


print(S2.rotation_matrix, "*", K, '+', S2.translation_vector, "\n")

print("L'atome d'arrivé a comme coordonnées : {}\n".format(K_sym))

#Représentation selon jupyter-jsmol
view = quick_view(conv_struc,supercell=[1,1,1])
display(view)
view.script('draw symop 7 {atomno = 1}; select atomno=1; label on; color red')

L'atome de départ a comme coordonnées: [0.25, 0.25, 0.25]

L'opérartion est une rotation de 90 degrés dans le plan xy. 

Rot:
[[ 0.  1.  0.]
 [-1.  0.  0.]
 [ 0.  0.  1.]]
tau
[0. 0. 0.] 

L'opération se calcule donc de la façon suivante : 

[[ 0.  1.  0.]
 [-1.  0.  0.]
 [ 0.  0.  1.]] * [0.25, 0.25, 0.25] + [0. 0. 0.] 

L'atome d'arrivé a comme coordonnées : [ 0.25 -0.25  0.25]



JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [14]:
print("L'atome de départ a comme coordonnées: {}\n".format(Se2))

print("L'opérartion est une symétrie miroir par rapport au plan yz. \n")
print(S3, "\n")

print("L'opération se calcule donc de la façon suivante : \n")

print(S3.rotation_matrix, "*", Se2, '+', S3.translation_vector, "\n")

print("L'atome d'arrivé a comme coordonnées : {}\n".format(Se2_sym))

#Représentation selon jupyter-jsmol
view = quick_view(conv_struc,supercell=[1,1,1])
display(view)
view.script('draw symop 10 {atomno = 22}; select atomno=22; label on; color red')

L'atome de départ a comme coordonnées: [1.0, 0.5, 0.5]

L'opérartion est une symétrie miroir par rapport au plan yz. 

Rot:
[[-1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
tau
[0. 0. 0.] 

L'opération se calcule donc de la façon suivante : 

[[-1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]] * [1.0, 0.5, 0.5] + [0. 0. 0.] 

L'atome d'arrivé a comme coordonnées : [-1.   0.5  0.5]



JsmolView(layout=Layout(align_self='stretch', height='400px'))